#!/usr/bin/env php
<?php
define('PATH_BASE', __DIR__);
define('PATH_VENDOR', PATH_BASE . DIRECTORY_SEPARATOR . 'vendor');
define('PATH_PAWS_SRC', PATH_VENDOR . DIRECTORY_SEPARATOR . 'mlaxwong' . DIRECTORY_SEPARATOR . 'paws' . DIRECTORY_SEPARATOR . 'src');

// Load Composer's autoloader
require PATH_VENDOR . DIRECTORY_SEPARATOR . 'autoload.php';

// Load dotenv
if (file_exists(PATH_BASE. DIRECTORY_SEPARATOR . '.env'))  (new Dotenv\Dotenv(PATH_BASE))->load();

// Run appication
$app = require PATH_VENDOR . '/mlaxwong/paws/bootstrap/console.php';
$app->setVendorPath(PATH_VENDOR);
$app->run();